name: Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
        - uses: actions/checkout@v3
          # Test phpunit
        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: 8.0
              tools: composer:v2
        - name: Install dependencies
          run: composer install --prefer-dist --no-progress --no-suggest
        - name: Run tests
          run: vendor/bin/phpunit -c phpunit.xml.dist

